"""
train_retrained_v2_classifier.py — Train 4-class XGBoost fusion classifier
from the 32-feature dataset generated by generate_retrained_v2_data.py.

4-class trust labels (matching production):
  0 = reject_both   (neither model matched GT)
  1 = trust_rgb     (only RGB matched)
  2 = trust_ir      (only IR matched)
  3 = trust_both    (both matched)

XGBoost config matches production (400 trees, depth 6, lr 0.05).

Usage:
    python train_retrained_v2_classifier.py
    python train_retrained_v2_classifier.py --csv path/to/fusion_dataset.csv
"""

import argparse
import json
import re
from pathlib import Path

import joblib
import numpy as np
import pandas as pd
from sklearn.metrics import accuracy_score, classification_report, f1_score
from sklearn.model_selection import GroupShuffleSplit
from xgboost import XGBClassifier

FEATURE_COLS = [
    "rgb_max_conf", "rgb_mean_conf", "ir_max_conf", "ir_mean_conf",
    "rgb_img_mean", "rgb_img_std", "rgb_img_dynamic_range",
    "rgb_img_entropy", "rgb_sky_ground_ratio", "rgb_edge_density",
    "rgb_blurriness",
    "ir_img_mean", "ir_img_std", "ir_img_dynamic_range",
    "ir_img_entropy", "ir_sky_ground_ratio", "ir_edge_density",
    "ir_blurriness",
    "rgb_best_log_bbox_area", "rgb_best_aspect_ratio",
    "rgb_best_pos_x", "rgb_best_pos_y", "rgb_best_dist_to_center",
    "rgb_best_local_contrast", "rgb_best_target_bg_delta",
    "ir_best_log_bbox_area", "ir_best_aspect_ratio",
    "ir_best_pos_x", "ir_best_pos_y", "ir_best_dist_to_center",
    "ir_best_local_contrast", "ir_best_target_bg_delta",
]

LABEL_NAMES = {0: "reject_both", 1: "trust_rgb", 2: "trust_ir", 3: "trust_both"}

SEQ_RE = re.compile(r"^(.+?)(?:_f\d+|_frame\d+|_\d{4,})(?:_visible|_infrared)?$", re.I)


def extract_sequence_id(stem, source):
    m = SEQ_RE.match(stem)
    base = m.group(1).rstrip("_") if m else stem
    return f"{source}::{base}"


def sequence_split(df, test_size=0.25, seed=42):
    groups = df["sequence_id"].values
    gss = GroupShuffleSplit(n_splits=1, test_size=test_size, random_state=seed)
    train_idx, test_idx = next(gss.split(df, df["trust_label"], groups=groups))
    return train_idx, test_idx


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--csv", default="fusion_models/retrained_v2_32feat/fusion_dataset.csv")
    parser.add_argument("--output-dir", default="fusion_models/retrained_v2_32feat")
    parser.add_argument("--detection-only", action="store_true", default=False,
                        help="Only train on frames with at least one detection")
    args = parser.parse_args()

    out_dir = Path(args.output_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    print(f"Loading: {args.csv}")
    df = pd.read_csv(args.csv)
    print(f"  {len(df)} rows")

    # Trust label distribution
    for t in sorted(df["trust_label"].unique()):
        n = (df["trust_label"] == t).sum()
        print(f"  {LABEL_NAMES.get(t, '?'):15s} (class {t}): {n:,}")

    # Detection-only filter
    if args.detection_only:
        before = len(df)
        df = df[(df["rgb_max_conf"] > 0) | (df["ir_max_conf"] > 0)].copy()
        print(f"\n  Detection-only filter: {before:,} -> {len(df):,} "
              f"(removed {before - len(df):,} no-detection frames)")
        for t in sorted(df["trust_label"].unique()):
            n = (df["trust_label"] == t).sum()
            print(f"    {LABEL_NAMES.get(t, '?'):15s}: {n:,}")

    # Sequence-based split
    df["sequence_id"] = df.apply(
        lambda r: extract_sequence_id(r["stem"], r["source"]), axis=1)
    n_seqs = df["sequence_id"].nunique()
    print(f"\n  Sequences: {n_seqs}")

    train_idx, test_idx = sequence_split(df)
    X_train = df.iloc[train_idx][FEATURE_COLS].values
    X_test = df.iloc[test_idx][FEATURE_COLS].values
    y_train = df.iloc[train_idx]["trust_label"].values
    y_test = df.iloc[test_idx]["trust_label"].values
    src_test = df.iloc[test_idx]["source"].values

    print(f"  Train: {len(X_train):,}  Test: {len(X_test):,}")

    # Train XGBoost (matching production config)
    print("\nTraining XGBoost (400 trees, depth 6, lr 0.05)...")
    model = XGBClassifier(
        n_estimators=400,
        max_depth=6,
        learning_rate=0.05,
        subsample=0.8,
        colsample_bytree=0.8,
        objective="multi:softprob",
        num_class=4,
        eval_metric="mlogloss",
        tree_method="hist",
        random_state=42,
        n_jobs=-1,
    )
    model.fit(X_train, y_train, verbose=False)

    y_pred = model.predict(X_test)
    y_prob = model.predict_proba(X_test)

    acc = float(accuracy_score(y_test, y_pred))
    f1_macro = float(f1_score(y_test, y_pred, average="macro", zero_division=0))
    f1_weighted = float(f1_score(y_test, y_pred, average="weighted", zero_division=0))

    print(f"\n  Overall:")
    print(f"    Accuracy:      {acc:.4f}")
    print(f"    F1 (macro):    {f1_macro:.4f}")
    print(f"    F1 (weighted): {f1_weighted:.4f}")

    target_names = [LABEL_NAMES[i] for i in range(4)]
    report = classification_report(y_test, y_pred, target_names=target_names, zero_division=0)
    print(f"\n{report}")

    # Per-dataset breakdown
    print("  Per-dataset:")
    per_dataset = {}
    for ds in np.unique(src_test):
        mask = src_test == ds
        a = float(accuracy_score(y_test[mask], y_pred[mask]))
        fm = float(f1_score(y_test[mask], y_pred[mask], average="macro", zero_division=0))
        per_dataset[ds] = {"n": int(mask.sum()), "acc": a, "f1_macro": fm}
        print(f"    {ds:<20s} n={mask.sum():>6d}  acc={a:.4f}  f1m={fm:.4f}")

    # Feature importance
    importance = dict(zip(FEATURE_COLS, model.feature_importances_.tolist()))
    ranked = sorted(importance.items(), key=lambda x: x[1], reverse=True)
    print(f"\n  Feature importance:")
    for feat, imp in ranked:
        bar = "#" * int(imp * 50)
        print(f"    {feat:<32s} {imp:.4f}  {bar}")

    # Save model (same format as production)
    model_path = out_dir / "model.joblib"
    joblib.dump({"model": model, "features": FEATURE_COLS}, model_path)
    print(f"\n  Saved: {model_path}")

    metrics = {
        "tag": "fusion_retrained_v2_32feat",
        "n_features": len(FEATURE_COLS),
        "features": FEATURE_COLS,
        "n_train": int(len(X_train)),
        "n_test": int(len(X_test)),
        "accuracy": acc,
        "f1_macro": f1_macro,
        "f1_weighted": f1_weighted,
        "per_dataset": per_dataset,
        "feature_importance": importance,
        "detection_only": args.detection_only,
    }
    with open(out_dir / "metrics.json", "w") as f:
        json.dump(metrics, f, indent=2)
    print(f"  Saved: {out_dir / 'metrics.json'}")

    # Feature importance plot
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    feats_sorted = [f for f, _ in ranked]
    imps_sorted = [i for _, i in ranked]
    fig, ax = plt.subplots(figsize=(10, max(4, len(feats_sorted) * 0.4)))
    ax.barh(range(len(feats_sorted)), imps_sorted, color="#4C72B0", edgecolor="white")
    ax.set_yticks(range(len(feats_sorted)))
    ax.set_yticklabels(feats_sorted, fontsize=11)
    ax.invert_yaxis()
    ax.set_xlabel("Feature Importance (gain)")
    ax.set_title(f"Fusion Classifier (retrained_v2) - {acc:.3f} acc, {f1_macro:.3f} F1m")
    ax.spines["top"].set_visible(False)
    ax.spines["right"].set_visible(False)
    fig.tight_layout()
    fig.savefig(str(out_dir / "feature_importance.png"), dpi=200)
    plt.close(fig)
    print(f"  Saved: {out_dir / 'feature_importance.png'}")
    print("\nDone.")


if __name__ == "__main__":
    main()
