"""
train_classifier.py — Train fusion classifier (XGBoost + LR baseline).

Reads the CSV generated by generate_fusion_data.py, trains the classifier,
sweeps decision threshold on val, and saves the model + metrics.

Usage:
    python classifier/train_classifier.py
    python classifier/train_classifier.py --config classifier/config.yaml
"""

import argparse
import json
from pathlib import Path

import joblib
import numpy as np
import pandas as pd
import yaml
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import precision_recall_curve, average_precision_score
from sklearn.model_selection import train_test_split
from xgboost import XGBClassifier


# ---------------------------------------------------------------------------
# Config
# ---------------------------------------------------------------------------

def load_config(path="config.yaml"):
    with open(path, "r", encoding="utf-8") as f:
        return yaml.safe_load(f)


# ---------------------------------------------------------------------------
# Feature columns
# ---------------------------------------------------------------------------

# Metadata columns that are NEVER features
META_COLS = {"stem", "source", "label", "time_of_day"}

# Categorical columns that need one-hot encoding
CATEGORICAL_COLS = {"time_of_day"}


def get_feature_cols(df, mode):
    """
    Auto-discover feature columns from the CSV.

    All numeric columns that aren't metadata are treated as features.
    Categorical columns (time_of_day) are one-hot encoded.
    """
    # One-hot encode categoricals
    for col in CATEGORICAL_COLS:
        if col in df.columns:
            dummies = pd.get_dummies(df[col], prefix=col, drop_first=False)
            # Convert bool columns to int
            for c in dummies.columns:
                dummies[c] = dummies[c].astype(int)
            df[dummies.columns.tolist()] = dummies

    # Auto-detect numeric feature columns (everything except metadata)
    feature_cols = []
    for col in df.columns:
        if col in META_COLS:
            continue
        if df[col].dtype in [np.float64, np.int64, float, int]:
            feature_cols.append(col)
        elif col.startswith("time_of_day_"):
            feature_cols.append(col)

    return feature_cols


# ---------------------------------------------------------------------------
# Threshold sweep
# ---------------------------------------------------------------------------

def sweep_threshold(y_true, y_prob, precision_target=None, recall_target=None):
    """
    Sweep decision threshold, return best operating point.

    If targets are given, find the threshold that meets both and maximizes F1.
    Otherwise, find the threshold that maximizes F1.
    """
    precisions, recalls, thresholds = precision_recall_curve(y_true, y_prob)
    # precision_recall_curve returns n+1 precisions/recalls, n thresholds
    # Drop last element of P/R to align with thresholds
    precisions = precisions[:-1]
    recalls = recalls[:-1]

    f1s = 2 * precisions * recalls / (precisions + recalls + 1e-12)

    best_idx = -1
    best_f1 = -1

    for i in range(len(thresholds)):
        meets_p = precision_target is None or precisions[i] >= precision_target
        meets_r = recall_target is None or recalls[i] >= recall_target
        if meets_p and meets_r and f1s[i] > best_f1:
            best_f1 = f1s[i]
            best_idx = i

    # Fallback: if no threshold meets both targets, just maximize F1
    if best_idx < 0:
        best_idx = int(np.argmax(f1s))
        print("  WARNING: No threshold meets both P and R targets. Using best F1.")

    return {
        "threshold": float(thresholds[best_idx]),
        "precision": float(precisions[best_idx]),
        "recall": float(recalls[best_idx]),
        "f1": float(f1s[best_idx]),
    }


# ---------------------------------------------------------------------------
# Train one model
# ---------------------------------------------------------------------------

def train_model(X_train, y_train, X_val, y_val, model_type, cfg):
    """Train a classifier, return fitted model and val probabilities."""
    if model_type == "xgboost":
        xgb_cfg = cfg.get("xgboost", {})
        n_pos = y_train.sum()
        n_neg = len(y_train) - n_pos
        model = XGBClassifier(
            n_estimators=xgb_cfg.get("n_estimators", 200),
            max_depth=xgb_cfg.get("max_depth", 4),
            learning_rate=xgb_cfg.get("learning_rate", 0.1),
            min_child_weight=xgb_cfg.get("min_child_weight", 10),
            subsample=xgb_cfg.get("subsample", 0.8),
            colsample_bytree=xgb_cfg.get("colsample_bytree", 0.8),
            scale_pos_weight=float(n_neg / n_pos) if n_pos > 0 else 1.0,
            eval_metric=xgb_cfg.get("eval_metric", "aucpr"),
            random_state=42,
            verbosity=1,
        )
        model.fit(X_train, y_train,
                  eval_set=[(X_val, y_val)],
                  verbose=False)
    else:
        model = LogisticRegression(max_iter=1000, random_state=42,
                                   class_weight="balanced")
        model.fit(X_train, y_train)

    y_prob = model.predict_proba(X_val)[:, 1]
    return model, y_prob


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(description="Train fusion classifier")
    parser.add_argument("--config", default="config.yaml")
    parser.add_argument("--csv", default=None,
                        help="Path to fusion_dataset.csv (default: runs/fusion_dataset.csv)")
    args = parser.parse_args()

    cfg = load_config(args.config)
    out_dir = Path(cfg["output_dir"])
    out_dir.mkdir(parents=True, exist_ok=True)

    # Read fusion mode from generate step
    meta_path = out_dir / "fusion_meta.json"
    if meta_path.exists():
        with open(meta_path, "r") as f:
            meta = json.load(f)
        mode = meta["mode"]
    else:
        mode = "frame"  # safe default
    print(f"  Fusion mode: {mode}-level")

    csv_path = Path(args.csv) if args.csv else out_dir / "fusion_dataset.csv"
    print(f"Loading data from {csv_path}")
    df = pd.read_csv(csv_path)
    print(f"  {len(df)} rows, {df['label'].sum()} positive, "
          f"{len(df) - df['label'].sum()} negative")

    feature_cols = get_feature_cols(df, mode)
    print(f"  Features: {feature_cols}")

    X = df[feature_cols].values
    y = df["label"].values

    # Split by frame stem to prevent leakage (all candidates from one frame
    # go to the same split)
    stems = df["stem"].unique()
    train_stems, valtest_stems = train_test_split(
        stems, test_size=0.3, random_state=42)
    val_stems, test_stems = train_test_split(
        valtest_stems, test_size=0.5, random_state=42)

    train_mask = df["stem"].isin(train_stems)
    val_mask = df["stem"].isin(val_stems)
    test_mask = df["stem"].isin(test_stems)

    X_train, y_train = X[train_mask], y[train_mask]
    X_val, y_val = X[val_mask], y[val_mask]
    X_test, y_test = X[test_mask], y[test_mask]

    print(f"  Train: {len(X_train)}, Val: {len(X_val)}, Test: {len(X_test)}")

    # Train both models
    results = {}
    for model_type in ["xgboost", "logistic_regression"]:
        print(f"\n{'='*60}")
        print(f"Training {model_type}...")
        model, y_prob_val = train_model(X_train, y_train, X_val, y_val,
                                        model_type, cfg)

        # Sweep threshold on val
        best = sweep_threshold(y_val, y_prob_val)
        print(f"  Val best: P={best['precision']:.4f}, R={best['recall']:.4f}, "
              f"F1={best['f1']:.4f} @ t={best['threshold']:.3f}")

        # Evaluate on test at frozen threshold
        y_prob_test = model.predict_proba(X_test)[:, 1]
        preds_test = (y_prob_test >= best["threshold"]).astype(int)

        tp = int(((preds_test == 1) & (y_test == 1)).sum())
        fp = int(((preds_test == 1) & (y_test == 0)).sum())
        fn = int(((preds_test == 0) & (y_test == 1)).sum())
        tn = int(((preds_test == 0) & (y_test == 0)).sum())

        test_p = tp / (tp + fp) if (tp + fp) > 0 else 0
        test_r = tp / (tp + fn) if (tp + fn) > 0 else 0
        test_f1 = 2 * test_p * test_r / (test_p + test_r) if (test_p + test_r) > 0 else 0
        aucpr = float(average_precision_score(y_test, y_prob_test))

        test_metrics = {
            "precision": test_p, "recall": test_r, "f1": test_f1,
            "aucpr": aucpr,
            "threshold": best["threshold"],
            "tp": tp, "fp": fp, "fn": fn, "tn": tn,
        }
        print(f"  Test:  P={test_p:.4f}, R={test_r:.4f}, F1={test_f1:.4f}, "
              f"AUC-PR={aucpr:.4f}")

        results[model_type] = {
            "val": best,
            "test": test_metrics,
        }

        # Save the primary model
        if model_type == cfg.get("classifier_type", "xgboost"):
            model_path = out_dir / "classifier.joblib"
            joblib.dump({
                "model": model,
                "feature_cols": feature_cols,
                "threshold": best["threshold"],
                "model_type": model_type,
                "fusion_mode": mode,
            }, model_path)
            print(f"  Saved model to {model_path}")

            # Feature importance (XGBoost only)
            if model_type == "xgboost":
                importances = dict(zip(feature_cols,
                                       model.feature_importances_.tolist()))
                results[model_type]["feature_importance"] = importances

                # Print ranked table
                ranked = sorted(importances.items(), key=lambda x: x[1], reverse=True)
                print(f"\n  Feature importance (ranked):")
                for feat, imp in ranked:
                    bar = "█" * int(imp * 50)
                    print(f"    {feat:<25s} {imp:.4f}  {bar}")

                # Save thesis-ready plot
                import matplotlib
                matplotlib.use("Agg")
                import matplotlib.pyplot as plt

                feats_sorted = [f for f, _ in ranked]
                imps_sorted = [i for _, i in ranked]

                fig, ax = plt.subplots(figsize=(10, max(4, len(feats_sorted) * 0.4)))
                y_pos = range(len(feats_sorted))
                bars = ax.barh(y_pos, imps_sorted, color="#4C72B0", edgecolor="white")
                ax.set_yticks(y_pos)
                ax.set_yticklabels(feats_sorted, fontsize=11)
                ax.invert_yaxis()
                ax.set_xlabel("Feature Importance (gain)", fontsize=12)
                ax.set_title("Fusion Classifier — Feature Importance", fontsize=14, pad=15)
                ax.spines["top"].set_visible(False)
                ax.spines["right"].set_visible(False)

                # Annotate bars with values
                for bar, imp in zip(bars, imps_sorted):
                    ax.text(bar.get_width() + 0.005, bar.get_y() + bar.get_height()/2,
                            f"{imp:.3f}", va="center", fontsize=9, color="#333")

                fig.tight_layout()
                plot_path = out_dir / "feature_importance.png"
                fig.savefig(str(plot_path), dpi=200)
                plt.close(fig)
                print(f"  Saved feature importance plot to {plot_path}")

    # Save all results
    metrics_path = out_dir / "metrics.json"
    with open(metrics_path, "w") as f:
        json.dump(results, f, indent=2)
    print(f"\nMetrics saved to {metrics_path}")


if __name__ == "__main__":
    main()
