#!/usr/bin/env python
"""gen_models_appendix.py — generate the 'Models Evaluated' appendix (app:models) in
docs/thesis_working.tex directly from knowledge/models.csv, so the table cannot drift
from the knowledge base. Idempotent: replaces the block between the BEGIN/END markers.

  py docs/gen_models_appendix.py
"""
import csv, re, sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
MODELS = ROOT / "knowledge" / "models.csv"
THESIS = Path(sys.argv[1]) if len(sys.argv) > 1 else ROOT / "docs" / "thesis_working.tex"
BEGIN = "% === BEGIN app:models (generated by docs/gen_models_appendix.py) ==="
END = "% === END app:models ==="

TYPE_LABEL = {
    "rgb_yolo": "RGB detectors (YOLOv26n)",
    "ir_yolo": "IR detectors (YOLOv26n, thermal)",
    "classifier": "Trust classifiers (fusion / routing)",
    "verifier": "Patch verifiers (MobileNetV3)",
    "mlp": "Distilled feature-space verifiers (MLP)",
}
TYPE_ORDER = ["rgb_yolo", "ir_yolo", "classifier", "verifier", "mlp"]


def esc(s: str) -> str:
    s = (s or "").strip()
    for k, v in {"≈": "approx", "×": "x", "→": "->", "≤": "<=", "≥": ">=",
                 "±": "+/-", "–": "-", "—": "-"}.items():
        s = s.replace(k, v)
    s = s.replace("\\", "/").replace("&", "+").replace("%", "\\%").replace("_", "\\_")
    s = s.replace("#", "\\#").replace("$", "\\$").replace("{", "(").replace("}", ")")
    s = re.sub(r"\s+", " ", s)
    return s


def note(r: dict) -> str:
    n = r.get("provenance_notes", "") or r.get("purpose_tags", "")
    n = esc(n)
    return (n[:72] + "...") if len(n) > 75 else n


def main() -> int:
    rows = list(csv.DictReader(open(MODELS, encoding="utf-8")))
    L = [BEGIN,
         "\\chapter{Models Evaluated}", "\\label{app:models}", "",
         "This appendix is the complete record of every model trained or evaluated in the course "
         "of this thesis, generated directly from \\texttt{knowledge/models.csv}. The main text "
         "narrates only the load-bearing comparisons (the production picks and the variants that "
         "change a decision or reveal a mechanism); the remaining rows are intermediate or "
         "superseded variants retained here for completeness and reproducibility. ``Status'' marks "
         "the current production pick; ``Lifecycle'' is \\texttt{active} (kept as a comparison), "
         "\\texttt{superseded} (replaced in the production lineage), or \\texttt{archived}.", "",
         "\\footnotesize",
         "\\begin{longtable}{p{0.30\\textwidth}llp{0.42\\textwidth}}",
         "\\toprule",
         "Model & Status & Lifecycle & Note \\\\", "\\midrule", "\\endhead"]
    total = 0
    for t in TYPE_ORDER:
        grp = [r for r in rows if r.get("type") == t]
        if not grp:
            continue
        grp.sort(key=lambda r: (r.get("production") != "yes",
                                {"active": 0, "superseded": 1, "archived": 2}.get(r.get("lifecycle"), 3),
                                r.get("id", "")))
        L.append("\\multicolumn{4}{l}{\\textbf{%s} (%d)} \\\\" % (esc(TYPE_LABEL[t]), len(grp)))
        L.append("\\midrule")
        for r in grp:
            status = "\\textbf{production}" if r.get("production") == "yes" else "---"
            L.append("\\texttt{%s} & %s & %s & %s \\\\" % (
                esc(r.get("id", "")), status, esc(r.get("lifecycle", "")), note(r)))
            total += 1
        L.append("\\midrule")
    L += ["\\bottomrule",
          "\\caption{All %d models trained or evaluated in this thesis (source: "
          "\\texttt{knowledge/models.csv}, %d production / %d active / %d superseded / %d archived).}"
          % (total,
             sum(1 for r in rows if r.get("production") == "yes"),
             sum(1 for r in rows if r.get("lifecycle") == "active"),
             sum(1 for r in rows if r.get("lifecycle") == "superseded"),
             sum(1 for r in rows if r.get("lifecycle") == "archived")),
          "\\label{tab:models_evaluated}",
          "\\end{longtable}", "\\normalsize", "", END, ""]
    block = "\n".join(L)

    tex = THESIS.read_text(encoding="utf-8")
    if BEGIN in tex and END in tex:                      # idempotent replace
        tex = re.sub(re.escape(BEGIN) + r".*?" + re.escape(END) + r"\n?", lambda _m: block, tex, flags=re.S)
    else:
        anchor = "\\chapter{Glossary of Abbreviations and Shorthand}"
        assert anchor in tex, "glossary anchor not found"
        tex = tex.replace(anchor, block + "\n" + anchor, 1)
    THESIS.write_text(tex, encoding="utf-8")
    print(f"app:models written — {total} models across {len([t for t in TYPE_ORDER if any(r.get('type')==t for r in rows)])} type groups")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
